function []= parameters_space_GUI(action)
% Used for the simulation parameter display, and alter
global  param_B param_C param_Tt   

if nargin<1,
    action='initialize';
end

if strcmp(action,'initialize'),
    %action='initialize'

    namestr = 'parameters_space_GUI';
    [existFlag]=figflag(namestr);
    if ~existFlag,
        % Now initialize the whole figure...
      
        figure( ...
            'Name','parameters_space_GUI', ...
            'NumberTitle','off', ...
            'Visible','on', ...
            'Color',0.8*[1 1 1], ...
            'BackingStore','off', ...
            'Position',[950 200 400 400]); %[x_pos, y_pos, width, height]
 %       colordef(figNumber,'white')
 %     else   clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));;
    end    
        axes( ...
            'Units','normalized', ...
            'Position',[0.05 0.05 0.030 0.040], ...
            'Visible','off');

        %===================================
        % Information for all buttons        
        %===================================
        labelColor=[0.8 0.8 0.8];
        top=0.95;
        bottom=0.05;
        btnWid=0.30;  % button width in the left coloumn
        btnWid2=0.42; % button width in the right coloumn
        btnHt=0.18/4;
        right=0.40;
        left=right-btnWid;
        spacing=0.02; % Spacing between the button and the next command's label
    
        %==================================%
        %====     The CONSOLE frames    ===%
        %==================================%
        frmBorder=0.03; %left coloumn
        frmPos=[left-frmBorder bottom-frmBorder btnWid+2*frmBorder 0.90+2*frmBorder];  %[x_pos, y_pos, width, height]
        uicontrol( ...
            'Style','frame', ...
            'Units','normalized', ...
            'Position',frmPos, ...
            'BackgroundColor',[0.50 0.50 0.70]); % light blue

        frmPos=[left+frmBorder+btnWid+0.03 bottom-frmBorder btnWid2+2*frmBorder 0.90+2*frmBorder]; %right coloumn
        uicontrol( ...
            'Style','frame', ...
            'Units','normalized', ...
            'Position',frmPos, ...
            'BackgroundColor',[0.50 0.50 0.70]); % light blue

        %====================================
        % The first button
        %====================================
        callbackStr='parameters_space_GUI(''build'');';
        labelPos=[left top-btnHt btnWid btnHt];
        %====================================
        % The General Paremeters button
        %====================================
        % Generic button information
        uicontrol( ...
            'Style','text', ...
            'String','Simulation Parameters', ...
            'Units','normalized', ...
            'Position',labelPos);
        labelPos(1,2)=labelPos(1,2)-btnHt;
        % The alternative options 1
        uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]); %left spacing of button 1
        uicontrol( ...
            'Style','togglebutton', ...
            'Tag','Bo1', ...
            'Units','normalized',...
            'String','General Parameters', ...
            'Value',param_B(1),...
            'sliderstep', [0 1], ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
            'Callback','parameters_space_GUI(''alternative'');'); %Button 1.  
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]); % right spacing
        labelPos(1,2)=labelPos(1,2)-btnHt;
        % The alternative options 2
% mark        i=i+1;

        uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);
        uicontrol( ...
            'Style','togglebutton', ...
            'Tag','Bo2', ...
            'Units','normalized',...
            'String','Space Object', ...
            'Value',param_B(2),...
            'sliderstep', [0 1], ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
            'Callback','parameters_space_GUI(''alternative'');');
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt;
         % The alternative options 3 ('Unused')
% mark        i=i+1;
         uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);
        uicontrol( ...
            'Style','togglebutton', ...
            'Tag','Bo3', ...
            'Units','normalized',...
            'String','Simulation Paramerets', ...
            'Value',param_B(3),...
            'sliderstep', [0 1], ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
            'Callback','parameters_space_GUI(''alternative'');');
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt;
        labelPos(1,2)=labelPos(1,2)-spacing;

        %=========================================
        % The run, stop, pause, continue buttons =
        %=========================================
        % Generic button information
        uicontrol( ...
            'Style','text', ...
            'String','Simulation', ...
            'Units','normalized', ...
            'Position',labelPos);
        labelPos(1,2)=labelPos(1,2)-btnHt;
        if param_C(1)==1
            uicontrol( ...
                   'Style','text', ...
                   'String','', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);
            uicontrol( ...
                'Style','pushbutton', ...
                'Tag','Co1', ...
                'Units','normalized',...
                'String','run', ...
                'Value',param_C(1),...
                'sliderstep', [0 1], ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''run'');');    
            uicontrol( ...
                    'Style','text', ...
                    'String','', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;
        elseif param_C(2)==1
            uicontrol( ...
                   'Style','text', ...
                   'String','', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);
            uicontrol( ...
                'Style','pushbutton', ...
                'Tag','Co2', ...
                'Units','normalized',...
                'String','pause', ...
                'Value',param_C(2),...
                'sliderstep', [0 1], ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''pause'');');
            uicontrol( ...
                    'Style','text', ...
                    'String','', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;
        elseif param_C(3)==1            
            uicontrol( ...
                   'Style','text', ...
                   'String','', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);
            uicontrol( ...
                'Style','pushbutton', ...
                'Tag','Co3', ...
                'Units','normalized',...
                'String','continue', ...
                'Value',param_C(3),...
                'sliderstep', [0 1], ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''continue'');');
            uicontrol( ...
                    'Style','text', ...
                    'String','', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;            
        end;
        if param_C(4)==1
            uicontrol( ...
                   'Style','text', ...
                   'String','', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);
            uicontrol( ...
                'Style','pushbutton', ...
                'Tag','Co4', ...
                'Units','normalized',...
                'String','stop', ...
                'Value',param_C(4),...
                'sliderstep', [0 1], ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''stop'');');
            uicontrol( ...
                    'Style','text', ...
                    'String','', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;
        end;
        labelPos(1,2)=labelPos(1,2)-spacing;

       global w_pos w_size         
        %============================
        %==  Window Position Reset ==
        %============================
        uicontrol( ...
            'Style','text', ...
            'String','Window reset', ...
            'Units','normalized', ...
            'Position',labelPos);
        labelPos(1,2)=labelPos(1,2)-btnHt;
                uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);
            
               uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);      
        uicontrol( ...
            'Style','pushbutton', ...
            'Units','normalized',...
            'String','Reset Window', ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
            'Callback','parameters_space_GUI(''Reset_Window_Position'');');
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt;           

        %==================================
        %==  Window Position Reset zoom  ==
        %==================================
               uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);      
        uicontrol( ...
            'Style','pushbutton', ...
            'Units','normalized',...
            'String','Reset to Zoom', ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
            'Callback','parameters_space_GUI(''Reset_Window_Position_zoom'');');
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt-spacing;           

        %========================
        %==    record video    ==
        %========================
        global enable_video 
        if enable_video    
            string='Video record ON';
        else
            string='Video record OFF';
        end
        uicontrol( ...
            'Style','text', ...
            'String','Video Record', ...
            'Units','normalized', ...
            'Position',labelPos);
        labelPos(1,2)=labelPos(1,2)-btnHt;
                uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);
        uicontrol( ...
            'Style','pushbutton', ...
            'String',string, ...
            'Units','normalized',...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
            'Callback','parameters_space_GUI(''record'');');    
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt-spacing;      
              
        %========================
        %==  The close button  ==
        %========================
        uicontrol( ...
            'Style','text', ...
            'String','Close GUI, and clear', ...
            'Units','normalized', ...
            'Position',labelPos);
        labelPos(1,2)=labelPos(1,2)-btnHt;
                uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);
        uicontrol( ...
            'Style','pushbutton', ...
            'String','close', ...
            'Units','normalized',...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
            'Callback','parameters_space_GUI(''close'');');    
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt-spacing;
        
        
        % bottom grey fill 
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1) 0.05 labelPos(1,3) labelPos(1,2)]);
    
        
        
       %===================================
       % Paremeters in the second coloumn
       %===================================
     
       labelPos=[left+frmBorder+btnWid+0.03+frmBorder top-btnHt btnWid2 btnHt];
       callbackStr2='parameters_space_GUI(''alternative'');';
       i=1;
       % Generic button information
 %mark      text=['Simulation Parameters' 'Space Object Parameters' 'Trailer Parameters'];
       index=param_B(1)+2*param_B(2)+3*param_B(3);
       if index==1 %General Parameters
        %===============================================================
        %= Display General Simulation Properties in the second coloumn =
        %===============================================================  
       global tidal_lock enable_trajectory_track enable_track_window w_pos w_size 
        uicontrol( ...
            'Style','text', ...
            'String','General Simulation Parameters', ...
            'Units','normalized', ...
            'Position',labelPos);
        labelPos(1,2)=labelPos(1,2)-btnHt-spacing;

        %==================
        %==  Tidal Lock  ==
        %==================
        uicontrol( ...
            'Style','text', ...
            'String','Options', ...
            'Units','normalized', ...
            'Position',labelPos);
        labelPos(1,2)=labelPos(1,2)-btnHt;
        if tidal_lock    
            string='Tidal Lock ON';
        else
            string='Tidal Lock OFF';
        end
        uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);      
        uicontrol( ...
            'Style','togglebutton', ...
            'Tag','TLock', ...
            'Units','normalized',...
            'String',string, ...
            'Value',tidal_lock,...
            'sliderstep', [0 1], ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
            'Callback','parameters_space_GUI(''TLock'');');
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt;%-spacing;

        %==================================
        %==  Tracking trajectory on/off  ==
        %==================================
        if enable_trajectory_track    
            string='Trajectory tracking';
        else
            string='Trajectory tracking OFF';
        end
        uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);      
        uicontrol( ...
            'Style','togglebutton', ...
            'Tag','TTrack', ...
            'Units','normalized',...
            'String',string, ...
            'Value',enable_trajectory_track,...
            'sliderstep', [0 1], ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
            'Callback','parameters_space_GUI(''TrajectoryTrack'');');
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt-spacing;
             
        
% Animation window position
            uicontrol( ...
                'Style','text', ...
                'String','Animation Window', ...
                'Units','normalized', ...
                'Position',labelPos);
            labelPos(1,2)=labelPos(1,2)-btnHt; 
            uicontrol( ...
                'Style','text', ...
                'String','Lower Left Coordinates', ...
                'Units','normalized', ...
                'Position',labelPos);
            labelPos(1,2)=labelPos(1,2)-btnHt;    
                uicontrol( ...
                'Style','text', ...
                'String','w_pos[x y]', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','w_pos_x', ...
                'Units','normalized',...
                'String',w_pos(1)/1000, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.40 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_animation'');');
            uicontrol( ...
                'Style','edit', ...
                'Tag','w_pos_y', ...
                'Units','normalized',...
                'String',w_pos(2)/1000, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.63 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_animation'');');
            uicontrol( ...
                'Style','text', ...
                'String','km', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.86 labelPos(1,2) labelPos(1,3)*0.14 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt; %-spacing

            
            % Animation window size
            uicontrol( ...
                'Style','text', ...
                'String','Window Size', ...
                'Units','normalized', ...
                'Position',labelPos);
            labelPos(1,2)=labelPos(1,2)-btnHt;    
                uicontrol( ...
                'Style','text', ...
                'String','w_size[x y]', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','w_size_x', ...
                'Units','normalized',...
                'String',w_size(1)/1000, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.40 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_animation'');');
            uicontrol( ...
                'Style','text', ...
                'Tag','w_size_y', ...
                'Units','normalized',...
                'String',w_size(2)/1000, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.63 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)]);
            uicontrol( ...
                'Style','text', ...
                'String','km', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.86 labelPos(1,2) labelPos(1,3)*0.14 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt-spacing;
 
        %===========================
        %==  Track or Zoom Window ==
        %===========================
        uicontrol( ...
            'Style','text', ...
            'String','Options', ...
            'Units','normalized', ...
            'Position',labelPos);
        labelPos(1,2)=labelPos(1,2)-btnHt;
        if enable_track_window    
            string='Track object on window';
        else
            string='Zoom window to fit object';
        end
        uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);      
        uicontrol( ...
            'Style','togglebutton', ...
            'Tag','OTrack', ...
            'Units','normalized',...
            'String',string, ...
            'Value',enable_track_window,...
            'sliderstep', [0 1], ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
            'Callback','parameters_space_GUI(''WindowTrack'');');
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt;%-spacing;
        
            
        %============================
        %==  Window Position Reset ==
        %============================
               uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);      
        uicontrol( ...
            'Style','pushbutton', ...
            'Units','normalized',...
            'String','Reset Window Position', ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
            'Callback','parameters_space_GUI(''Reset_Window_Position'');');
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt;           

        %==================================
        %==  Window Position Reset zoom  ==
        %==================================
               uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);      
        uicontrol( ...
            'Style','pushbutton', ...
            'Units','normalized',...
            'String','Reset Window Position zoom', ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
            'Callback','parameters_space_GUI(''Reset_Window_Position_zoom'');');
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt-spacing;           

        
elseif index==2 %Space Object
        %=========================================================
        %= Display Space Object Properties in the second coloumn =
        %=========================================================  
          global cm I l m_sw w ObjectLengthAnim v_Object_0 swSPpos0 r_earth
          
         % param_Tt(1) 'Speed'
         % param_Tt(2) 'Height'
         % param_Tt(3) 'Mass, Inertia'
         % param_Tt(4) 'Geometry'
         % param_Tt(5) 'Protrution'
          
       callbackStralt='parameters_space_GUI(''alternative_tractor'');';  
 
        uicontrol( ...
            'Style','text', ...
            'String','Space Object Parameters', ...
            'Units','normalized', ...
            'Position',labelPos);
        labelPos(1,2)=labelPos(1,2)-btnHt-spacing;
 
        %=====================================
        % ===      Set Initial speed       ===
        %=====================================       
        uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.03 labelPos(1,4)]);   
        uicontrol( ...
            'Style','togglebutton', ...
            'String','Initial Speed', ...
            'Tag','To1', ...
            'Value',param_Tt(1),...
            'sliderstep', [0 1], ...
            'Units','normalized', ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.03 labelPos(1,2) labelPos(1,3)*0.94 labelPos(1,4)],...
            'Callback',callbackStralt);
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.97 labelPos(1,2) labelPos(1,3)*0.03 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt;   
        if param_Tt(1)==1 % Space Object Initial Speed     
            uicontrol( ...
                   'Style','text', ...
                   'String','v0_x=', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','v0_x', ...
                'Units','normalized',...
                'String',v_Object_0(1)/1000, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.40 labelPos(1,2) labelPos(1,3)*0.35 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''speed'');');
            uicontrol( ...
                    'Style','text', ...
                    'String','km/s', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.75 labelPos(1,2) labelPos(1,3)*0.25 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;%-spacing;
            uicontrol( ...
                   'Style','text', ...
                   'String','v0_y=', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','v0_y', ...
                'Units','normalized',...
                'String',v_Object_0(2)/1000, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.40 labelPos(1,2) labelPos(1,3)*0.35 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''speed'');');
            uicontrol( ...
                    'Style','text', ...
                    'String','km/s', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.75 labelPos(1,2) labelPos(1,3)*0.25 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;%-spacing;        
            uicontrol( ...
                   'Style','text', ...
                   'String','v0_z=', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','v0_z', ...
                'Units','normalized',...
                'String',v_Object_0(3)/1000, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.40 labelPos(1,2) labelPos(1,3)*0.35 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''speed'');');
            uicontrol( ...
                    'Style','text', ...
                    'String','km/s', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.75 labelPos(1,2) labelPos(1,3)*0.25 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;%-spacing;
        %====================================
        %==   Object Speed Reset to Custom ==
        %====================================
                   uicontrol( ...
                   'Style','text', ...
                   'String','', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);      
            uicontrol( ...
                'Style','pushbutton', ...
                'Units','normalized',...
                'String','Reset Object Speed', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''Reset_Object_Speed'');'); 

            uicontrol( ...
                    'Style','text', ...
                    'String','', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt; 
        %========================================
        %==   Object Speed Reset to 1st Cosmic ==
        %========================================
                   uicontrol( ...
                   'Style','text', ...
                   'String','', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);      
            uicontrol( ...
                'Style','pushbutton', ...
                'Units','normalized',...
                'String','Reset to 1st Cosmic Speed', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''Reset_Object_Speed1st'');'); 

            uicontrol( ...
                    'Style','text', ...
                    'String','', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;
        %========================================
        %==   Object Speed Reset to 2nd Cosmic ==
        %========================================
                   uicontrol( ...
                   'Style','text', ...
                   'String','', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);      
            uicontrol( ...
                'Style','pushbutton', ...
                'Units','normalized',...
                'String','Reset to 2nd Cosmic Speed', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''Reset_Object_Speed2nd'');'); 

            uicontrol( ...
                    'Style','text', ...
                    'String','', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt-spacing; 
        end
        
        %=====================================
        % ===       Initial height         ===
        %=====================================       
        uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.03 labelPos(1,4)]);   
        uicontrol( ...
            'Style','togglebutton', ...
            'String','Initial Height', ...
            'Tag','To2', ...
            'Value',param_Tt(2),...
            'sliderstep', [0 1], ...
            'Units','normalized', ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.03 labelPos(1,2) labelPos(1,3)*0.94 labelPos(1,4)],...
            'Callback',callbackStralt);
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.97 labelPos(1,2) labelPos(1,3)*0.03 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt;   
        if param_Tt(2)==1 % Space Object Initial Height     
            uicontrol( ...
                   'Style','text', ...
                   'String','h_x=', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','h_x', ...
                'Units','normalized',...
                'String',swSPpos0(1)/1000, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.40 labelPos(1,2) labelPos(1,3)*0.35 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''height'');');
            uicontrol( ...
                    'Style','text', ...
                    'String','km', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.75 labelPos(1,2) labelPos(1,3)*0.25 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;%-spacing;
                        uicontrol( ...
                   'Style','text', ...
                   'String','h_y=', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','h_y', ...
                'Units','normalized',...
                'String',swSPpos0(2)/1000, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.40 labelPos(1,2) labelPos(1,3)*0.35 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''height'');');
            uicontrol( ...
                    'Style','text', ...
                    'String','km', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.75 labelPos(1,2) labelPos(1,3)*0.25 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;%-spacing;
                        uicontrol( ...
                   'Style','text', ...
                   'String','h_z=', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','h_z', ...
                'Units','normalized',...
                'String',swSPpos0(3)/1000, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.40 labelPos(1,2) labelPos(1,3)*0.35 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''height'');');
            uicontrol( ...
                    'Style','text', ...
                    'String','km', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.75 labelPos(1,2) labelPos(1,3)*0.25 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;%-spacing;
            %============================
            %==  Object Position Reset ==
            %============================
                   uicontrol( ...
                   'Style','text', ...
                   'String','', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.05 labelPos(1,4)]);      
            uicontrol( ...
                'Style','pushbutton', ...
                'Units','normalized',...
                'String','Reset Object Position', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.05 labelPos(1,2) labelPos(1,3)*0.9 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''Reset_Object_Position'');');
            uicontrol( ...
                    'Style','text', ...
                    'String','', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt-spacing; 
        end        
     
        %=====================================
        % Space Object Mass, Inertia
        %=====================================       
  
        uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.03 labelPos(1,4)]);          
        uicontrol( ...
            'Style','togglebutton', ...
            'String','Mass, Inertia', ...
            'Tag','To3', ...
            'Value',param_Tt(3),...
            'sliderstep', [0 1], ...
            'Units','normalized', ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.03 labelPos(1,2) labelPos(1,3)*0.94 labelPos(1,4)],...
            'Callback',callbackStralt);
         uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.97 labelPos(1,2) labelPos(1,3)*0.03 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt;          
        
        if param_Tt(3)==1 % Display Space Object Mass Properties
            
            uicontrol( ...
                'Style','text', ...
                'String','m=', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','m', ...
                'Units','normalized',...
                'String',m_sw, ...      
                'Position',[labelPos(1,1)+labelPos(1,3)*0.40 labelPos(1,2) labelPos(1,3)*0.35 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','text', ...
                'String','kg', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.75 labelPos(1,2) labelPos(1,3)*0.25 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;
            
            uicontrol( ...
                'Style','text', ...
                'String','Ixyz=', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1:2) labelPos(1,3)*0.20 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','I1', ...
                'Units','normalized',...
                'String',101, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.20 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','edit', ...
                'Tag','I2', ...
                'Units','normalized',...
                'String',102, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.43 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','edit', ...
                'Tag','I3', ...
                'Units','normalized',...
                'String',103, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.66 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','text', ...
                'String','104', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.89 labelPos(1,2) labelPos(1,3)*0.11 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt-spacing;
        end % Display Object Mass Properties 
        %==================================
        %===    Space Object Geometry   ===
        %==================================      
        
        uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.03 labelPos(1,4)]);       
        uicontrol( ...
            'Style','togglebutton', ...
            'String','Geometry', ...
            'Tag','To4', ...
            'Value',param_Tt(4),...
            'Units','normalized', ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.03 labelPos(1,2) labelPos(1,3)*0.94 labelPos(1,4)],...
            'Callback',callbackStralt);
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.97 labelPos(1,2) labelPos(1,3)*0.03 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt;
        
        
        if param_Tt(4)==1 % Display Space Object Geometry Properties
        
            uicontrol( ...
                'Style','text', ...
                'String','l=', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','l', ...
                'Units','normalized',...
                'String',l, ...         
                'Position',[labelPos(1,1)+labelPos(1,3)*0.40 labelPos(1,2) labelPos(1,3)*0.35 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','text', ...
                'String','m', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.75 labelPos(1,2) labelPos(1,3)*0.25 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;
            uicontrol( ...
                'Style','text', ...
                'String','w=', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','w', ...
                'Units','normalized',...
                'String',w, ...         
                'Position',[labelPos(1,1)+labelPos(1,3)*0.40 labelPos(1,2) labelPos(1,3)*0.35 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','text', ...
                'String','m', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.75 labelPos(1,2) labelPos(1,3)*0.25 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;
            
            uicontrol( ...
                'Style','text', ...
                'String','cm=', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1:2) labelPos(1,3)*0.26 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','cm1', ...
                'Units','normalized',...
                'String',cm(1), ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.26 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','edit', ...
                'Tag','cm2', ...
                'Units','normalized',...
                'String',cm(2), ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.49 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','edit', ...
                'Tag','cm3', ...
                'Units','normalized',...
                'String',cm(3), ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.72 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','text', ...
                'String','m', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;
            
            uicontrol( ...
                'Style','text', ...
                'String','OLA=', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1:2) labelPos(1,3)*0.26 labelPos(1,4)]);      %OLA is ObjectLengthAnim 
            uicontrol( ...
                'Style','edit', ...
                'Tag','ObjectLengthAnim1', ...
                'Units','normalized',...
                'String',ObjectLengthAnim(1), ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.26 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','edit', ...
                'Tag','ObjectLengthAnim2', ...
                'Units','normalized',...
                'String',ObjectLengthAnim(2), ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.49 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','edit', ...
                'Tag','ObjectLengthAnim3', ...
                'Units','normalized',...
                'String',ObjectLengthAnim(3), ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.72 labelPos(1,2) labelPos(1,3)*0.23 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','text', ...
                'String','m', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.95 labelPos(1,2) labelPos(1,3)*0.05 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;
            
        end % Display Space Object Geometry Properties
             
        %==============================================
        %==  Space Object Protrution Parameters  ==
        %==============================================      
        uicontrol( ...
               'Style','text', ...
               'String','', ...
               'Units','normalized', ...
               'Position',[labelPos(1,1:2) labelPos(1,3)*0.03 labelPos(1,4)]);        
           uicontrol( ...
             'Style','togglebutton', ...
             'String','Protrution', ...
             'Tag','To5', ...
             'Value',param_Tt(5),...
             'sliderstep', [0 1], ...
             'Units','normalized', ...
            'Position',[labelPos(1,1)+labelPos(1,3)*0.03 labelPos(1,2) labelPos(1,3)*0.94 labelPos(1,4)],...
             'Callback',callbackStralt);
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.97 labelPos(1,2) labelPos(1,3)*0.03 labelPos(1,4)]);
        labelPos(1,2)=labelPos(1,2)-btnHt;  
        
           if param_Tt(5)==1 % Display Space Object Protrution Properties
             uicontrol( ...
                 'Style','text', ...
                 'String','Unused', ...
                 'Units','normalized', ...
                 'Position',labelPos);
             labelPos(1,2)=labelPos(1,2)-btnHt;
             uicontrol( ...
                'Style','text', ...
                'String','Unused', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','Drive_F', ...
                'Units','normalized',...
                'String',0, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.38 labelPos(1,2) labelPos(1,3)*0.22 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''build_tractor'');');
           uicontrol( ...
                'Style','text', ...
                'String',' /', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.60 labelPos(1,2) labelPos(1,3)*0.06 labelPos(1,4)]);
            uicontrol( ...
                'Style','text', ...
                'Tag','Drive_R', ...
                'Units','normalized',...
                'String',0, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.66 labelPos(1,2) labelPos(1,3)*0.22 labelPos(1,4)]);%, ...
   %             'Callback','parameters_space_GUI(''build_tractor'');');
            uicontrol( ...
                'Style','text', ...
                'String','%', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.88 labelPos(1,2) labelPos(1,3)*0.12 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt;
            
           end % Display Space Object Protrution Properties
           labelPos(1,2)=labelPos(1,2)-spacing;  
           uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1) 0.05 labelPos(1,3) labelPos(1,2)]); 
        
       labelPos(1,2)=labelPos(1,2)-spacing;
       elseif index==3 %Simulation Parameters
        %=======================================================
        %= Display Simulation Properties in the second coloumn =
        %=======================================================  
        global SimulationTimeStep
           uicontrol( ...
               'Style','text', ...
               'String','Simulation Parameters', ...
               'Units','normalized', ...
               'Position',labelPos);
           labelPos(1,2)=labelPos(1,2)-btnHt-spacing;                  

% Time step
            uicontrol( ...
                'Style','text', ...
                'String','Simlation Time Step Size', ...
                'Units','normalized', ...
                'Position',labelPos);
            labelPos(1,2)=labelPos(1,2)-btnHt;     
            uicontrol( ...
                   'Style','text', ...
                   'String','Ts =', ...
                   'Units','normalized', ...
                   'Position',[labelPos(1,1:2) labelPos(1,3)*0.40 labelPos(1,4)]);      
            uicontrol( ...
                'Style','edit', ...
                'Tag','STS', ...
                'Units','normalized',...
                'String',SimulationTimeStep, ...
                'Position',[labelPos(1,1)+labelPos(1,3)*0.40 labelPos(1,2) labelPos(1,3)*0.35 labelPos(1,4)], ...
                'Callback','parameters_space_GUI(''Simulation_Time_Step'');');
            uicontrol( ...
                    'Style','text', ...
                    'String','s', ...
                    'Units','normalized', ...
                    'Position',[labelPos(1,1)+labelPos(1,3)*0.75 labelPos(1,2) labelPos(1,3)*0.25 labelPos(1,4)]);
            labelPos(1,2)=labelPos(1,2)-btnHt-spacing;
            
        % bottom grey fill 
        uicontrol( ...
                'Style','text', ...
                'String','', ...
                'Units','normalized', ...
                'Position',[labelPos(1,1) 0.05 labelPos(1,3) labelPos(1,2)]); 
            
       end
            
       
elseif strcmp(action,'speed'),
%================================
%=====     action='speed'    ====
%================================
    global v_Object_0
    v_Object_0(1)=str2num(get(findobj(gcf,'Tag','v0_x'),'string'))*1000;
    v_Object_0(2)=str2num(get(findobj(gcf,'Tag','v0_y'),'string'))*1000;
    v_Object_0(3)=str2num(get(findobj(gcf,'Tag','v0_z'),'string'))*1000;
elseif strcmp(action,'height'),
%================================
%=====     action='height'    ====
%================================
    global swSPpos0 r_earth
    swSPpos0(1)=str2num(get(findobj(gcf,'Tag','h_x'),'string'))*1000;%+r_earth;
    swSPpos0(2)=str2num(get(findobj(gcf,'Tag','h_y'),'string'))*1000;%+r_earth;
    swSPpos0(3)=str2num(get(findobj(gcf,'Tag','h_z'),'string'))*1000;%+r_earth;
elseif strcmp(action,'run'),
%=============================
%====     action='run'    ====
%=============================
    global param_C
%    CurrFigNr = get(gcf,'Number');
    set_param('space_10','SimulationCommand','start')
    param_C=[0 1 0 1];
  %mark  clf(1);
  clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
    parameters_space_GUI;
    
elseif strcmp(action,'pause'),
%=============================
%====   action='pause'    ====
%=============================
    global param_C
 %   CurrFigNr = get(gcf,'Number');
    set_param('space_10','SimulationCommand','pause')
    param_C=[0 0 1 1];
      clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));;
    parameters_space_GUI;
    
elseif strcmp(action,'continue'),
%=============================
%====  action='continue'  ====
%=============================
    global param_C
%    CurrFigNr = get(gcf,'Number');
    set_param('space_10','SimulationCommand','continue')
    param_C=[0 1 0 1];
      clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));;
    parameters_space_GUI;
    
elseif strcmp(action,'stop'),
%=============================
%====    action='stop'    ====
%=============================
    global param_C
%    CurrFigNr = get(gcf,'Number')
    set_param('space_10','SimulationCommand','stop')
    param_C=[1 0 0 0];
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));;
    parameters_space_GUI;
        
elseif strcmp(action,'build_tractor'),
%====================================
%action='build_tractor'
%====================================
global cm I l m_sw w param_Tt ObjectLengthAnim
 
    if param_Tt(3)==1 % Space Object Mass, Inertia Parameters
           m_sw=str2double(get(findobj(gcf,'Tag','m'),'string'));
           I(:)=[str2double(get(findobj(gcf,'Tag','I1'),'string'))...
                 str2double(get(findobj(gcf,'Tag','I2'),'string'))...
                 str2double(get(findobj(gcf,'Tag','I3'),'string'))];
    elseif param_Tt(4)==1  % Space Object Geometry Parameters
           l=str2double(get(findobj(gcf,'Tag','l'),'string'));
           w=str2double(get(findobj(gcf,'Tag','w'),'string'));
           cm(:)=[str2double(get(findobj(gcf,'Tag','cm1'),'string'))...
                  str2double(get(findobj(gcf,'Tag','cm2'),'string'))...
                  str2double(get(findobj(gcf,'Tag','cm3'),'string'))];
           ObjectLengthAnim(:)=[str2double(get(findobj(gcf,'Tag','ObjectLengthAnim1'),'string'))...
                  str2double(get(findobj(gcf,'Tag','ObjectLengthAnim2'),'string'))...
                  str2double(get(findobj(gcf,'Tag','ObjectLengthAnim3'),'string'))];
    end 

elseif strcmp(action,'TLock'),
%================================
%==  action=Change tidal_lock  ==
%================================
    global tidal_lock 
    tidal_lock=~tidal_lock;
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
    parameters_space_GUI;

elseif strcmp(action,'TrajectoryTrack'),
%======================================
%==  action=Change Trajectory Track  ==
%======================================
    global enable_trajectory_track 
    enable_trajectory_track=~enable_trajectory_track;
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
    parameters_space_GUI;

elseif strcmp(action,'WindowTrack'),
%==================================
%==  action=Change Window Track  ==
%==================================
    global enable_track_window 
    enable_track_window=~enable_track_window;
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
    parameters_space_GUI;
    
elseif strcmp(action,'Reset_Window_Position'),
%======================================
%==   action=Reset Window Position   ==
%======================================
    init_parameters_space_GUI('initialize_Window');    
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
    parameters_space_GUI;
    
elseif strcmp(action,'Reset_Window_Position_zoom'),
%===========================================
%==   action=Reset Window Position zoom   ==
%===========================================
    init_parameters_space_GUI('initialize_Window_zoom');    
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
    parameters_space_GUI;
    
elseif strcmp(action,'Reset_Object_Position'),
%===========================================
%==   action=Reset Object Position Zoom   ==
%===========================================
    init_parameters_space_GUI('initialize_ObjectPosition');
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
    parameters_space_GUI;
elseif strcmp(action,'Reset_Object_Speed'),
%=============================================
%==   action=Reset Object Speed 1st Cosmic  ==
%=============================================
    init_parameters_space_GUI('initialize_ObjectSpeed');
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
    parameters_space_GUI;
elseif strcmp(action,'Reset_Object_Speed1st'),
%=============================================
%==   action=Reset Object Speed 2nd Cosmic  ==
%=============================================
    init_parameters_space_GUI('initialize_ObjectSpeed1st');
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
    parameters_space_GUI;
elseif strcmp(action,'Reset_Object_Speed2nd'),
%======================================
%==   action=Reset Object Speed   ==
%======================================
    init_parameters_space_GUI('initialize_ObjectSpeed2nd');
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
    parameters_space_GUI;
    
elseif strcmp(action,'build_animation'),
%===============================
%==  action='build_animation  ==
%===============================
    global w_pos w_size
    w_pos=[str2double(get(findobj(gcf,'Tag','w_pos_x'),'string')) ...
           str2double(get(findobj(gcf,'Tag','w_pos_y'),'string'))]*1000;
    w_size=[str2double(get(findobj(gcf,'Tag','w_size_x'),'string')) ...
            str2double(get(findobj(gcf,'Tag','w_size_x'),'string'))/1.5]*1000;
    w_pos=w_pos(1,:);
    w_size=w_size(1,:);
    set(findobj(gcf,'Tag','w_size_y'),'String',w_size(2)/1000);
       
elseif strcmp(action,'alternative'),
%===================================
%==  action=Alternative switches  ==
%===================================   
    figure(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number')); %set 'parameters_space_GUI' the current figure
    param_Bo1=get(findobj(gcf,'Tag','Bo1'),'Value');
    param_Bo2=get(findobj(gcf,'Tag','Bo2'),'Value');
    param_Bo3=get(findobj(gcf,'Tag','Bo3'),'Value');
    param_B=xor([param_Bo1 param_Bo2 param_Bo3],[param_B(1) param_B(2) param_B(3)]);
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number')); 
    parameters_space_GUI;
        
elseif strcmp(action,'alternative_tractor'),
%=========================================
%== action=Alternative switches Space Object ==
%=========================================
    figure(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number')); %set 'parameters_space_GUI' the current figure
    param_To1=get(findobj(gcf,'Tag','To1'),'Value');
    param_To2=get(findobj(gcf,'Tag','To2'),'Value');
    param_To3=get(findobj(gcf,'Tag','To3'),'Value');
    param_To4=get(findobj(gcf,'Tag','To4'),'Value');
    param_To5=get(findobj(gcf,'Tag','To5'),'Value');

    param_Tt=xor([param_To1   param_To2   param_To3   param_To4   param_To5],...
                 [param_Tt(1) param_Tt(2) param_Tt(3) param_Tt(4) param_Tt(5)]);
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
    parameters_space_GUI;

% elseif strcmp(action,'alternative_trailer'),
% %====================================
% %action=Alternative switches trailer
% %====================================
%     
%     param_Tot1=get(findobj(gcf,'Tag','Tot1'),'Value');
%     param_Tot2=get(findobj(gcf,'Tag','Tot2'),'Value');
%     param_Tot3=get(findobj(gcf,'Tag','Tot3'),'Value');
%     param_Tot4=get(findobj(gcf,'Tag','Tot4'),'Value');
%     param_Tot5=get(findobj(gcf,'Tag','Tot5'),'Value');
%     
%     param_Ttt=xor([param_Tot1 param_Tot2 param_Tot3 param_Tot4 param_Tot5],...
%                   [param_Ttt(1) param_Ttt(2) param_Ttt(3) param_Ttt(4) param_Ttt(5)]);
%       clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
%     parameters_space_GUI;
    
    elseif strcmp(action,'clear'),
    param_C=get(findobj(gcf,'Tag','C'),'Value');
 %   param_D=get(findobj(gcf,'Tag','D'),'Value');
    clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number'));
    parameters_space_GUI;
    
elseif strcmp(action,'record'),
%==============================
%==    Record animation      ==
%==============================
global enable_video
enable_video=~enable_video;
clf(get(findobj('Type','figure','Name','parameters_space_GUI'),'Number')); 
parameters_space_GUI; 

elseif strcmp(action,'Simulation_Time_Step'),
%===============================================
%=====     action='Simulation Time Step'    ====
%===============================================
global SimulationTimeStep
SimulationTimeStep=str2num(get(findobj(gcf,'Tag','STS'),'string'));
% parameters_space_GUI; 

elseif strcmp(action,'close'),
%==============================
%==  Closes Parameters GUI   ==
%==============================
[a,b]=figflag('parameters_space_GUI');
close(b);
clear global;
end;
